<?php
// Checksum file
// Product: vbprojecttools - vBulletin Project Tools
// Version: 2.2.0
// File generated by: $RCSfile: mh_md5gen.php,v $ - $Revision: 2.0.1 $
// Generator: MD5 Version File generator by MarcoH64 and PitchouneN64ngc (c)

$md5_sums = array(
	'/' => array(
		'issue.php' => '0b755296fb8598e94845c11d0d4c147f',
		'issuelist.php' => '9329c6a19e7ad52d2b9af71c59115ed7',
		'milestone.php' => 'acff1ec526a4c0a862b10ebd513b1a4b',
		'milestoneissuelist.php' => '70b3901c53a0e8ebebf496ce37bcef01',
		'project.php' => 'dcda6220d9c162c0fa91365db97a36ec',
		'projectajax.php' => 'e77cedac412097f492f03a0b442fe6e5',
		'projectattachment.php' => '5a25ec8ab6963bb55d0196c9dababf44',
		'projectexternal.php' => 'fe9f35ebd93cdfa4069caf72162f34e5',
		'projectmilestone.php' => 'a1d1aac47adc4a5446f5b04ee267cd8b',
		'projectpost.php' => '78153282ba713d36304353e3c4a1bb55',
		'projectsearch.php' => 'efc62f985a3d3b6fd2151e68b3691d17',
		'projecttimeline.php' => '6871b2386ba1e437dcd46519cd6231f5',
	),
	'/admincp' => array(
		'project.php' => '7e00ec65a88054e9eea8b26e6a2c79a7',
		'projectattachment.php' => '49839ef3bc440e92314f19ba6f08f065',
		'projectcategory.php' => '0ed386df63b1866ea20b22c2e7c6512f',
		'projectcounters.php' => 'ef9afcf2f2a1c036ff956d8eb279003b',
		'projectmagicselect.php' => '63430fa9bc8f11d98dc0b5d6b0044ef1',
		'projectmilestone.php' => 'beeaa9c5c6f28def5bc8154c09e943b3',
		'projectpermission.php' => '9dc7bb7eed7f47f59049a1c1ae62e5d8',
		'projectpriority.php' => '35737452832d29e2281dc14d0dbfd9d9',
		'projecttag.php' => '51eecf0d6a1947df8a76b647f206bad9',
		'projecttype.php' => '19171df64de9c08a2bec725407bdfb5f',
		'projectversion.php' => '9edc62bc06885ba6b992dbac98bb13db',
	),
	'/archive' => array(
		'project.php' => 'd3bea9d90bccfc7f61878e715103666d',
	),
	'/clientscript' => array(
		'vbulletin_list_builder.js' => '09dff26640daa5659d11e72bb0ac63db',
		'vbulletin_magic_select.js' => '3e39038ce65f73d7cafbfca839b8b085',
		'vbulletin_pt_ajax_issuelist.js' => 'ee27de4f589a0987e4e43cf88b70a57e',
		'vbulletin_pt_issue.js' => 'b3d83f09de9b9d679d66e30383935560',
		'vbulletin_pt_issuenote_loader.js' => '600c8823736eba0e85c6d47a1f4da908',
		'vbulletin_pt_petition.js' => '52ded1d3918b2e188e6e993051bd86e7',
		'vbulletin_pt_quick_reply.js' => 'e3bde79fef43f4bc3e0594f876cef2cc',
		'vbulletin_pt_read_marker.js' => '95ea61c41944bd9bad86348a46572f53',
		'vbulletin_ptsearch_form.js' => 'e211980d63d43931fa99f891a3ae1cbc',
		'vbulletin_quick_edit_issue.js' => '8bc52541230ee367c286a29f62799e28',
		'vbulletin_quick_edit_issuenote.js' => '41e82f944b29ff5765f55022045c49a0',
	),
	'/includes' => array(
		'adminfunctions_projecttools.php' => '9aa2aa20c506b03011e0a10e111adca6',
		'class_bbcode_pt.php' => 'b8657f072d41e6361ab03f2aa083f100',
		'class_dm_attachment_pt.php' => 'b24b3041af5d80871733f2edec16553d',
		'class_dm_pt_issue.php' => '9e1ce17db1d89fd1ff637ef931dd09d3',
		'class_dm_pt_issueassign.php' => '1130c677a32843ebc8a44fb407093d8b',
		'class_dm_pt_issuechange.php' => 'ee3c83f5429fbb34e749d8809654f2f2',
		'class_dm_pt_issuenote.php' => 'fb5a1ec7dac7ca7cd8091747afbfea07',
		'class_dm_pt_issuepetition.php' => 'f9696ed72a2aa35a0caf79d0fe39342b',
		'class_dm_pt_issuereport.php' => 'fe23e63c87b9bb171c01e89be7cf93ed',
		'class_dm_pt_issuestatus.php' => '7296b78d772f360a0359e321da959e57',
		'class_dm_pt_issuesubscribe.php' => 'bbfe3bad921d8425b446ac9e5b278474',
		'class_dm_pt_issuetype.php' => '372cbfbb0c3d89c855ef12ba7342f007',
		'class_dm_pt_issuevote.php' => '7c738810f38369964dc07590a1e07262',
		'class_dm_pt_magicselect.php' => '8f37c1ef6b6d0f79e603132939743f0f',
		'class_dm_pt_milestone.php' => 'fd225ef8928e3e2019833d8555761551',
		'class_dm_pt_project.php' => 'b21dc03e01c18bf812170a49fecd7405',
		'class_friendly_url_project.php' => 'f9ffd5a55381801b5fbce3ec99ddb7c1',
		'class_pt_impex.php' => '391aa186185a0dc04ab39d005d247a7b',
		'class_pt_issuelist.php' => 'd19967532f318354ae08bad667ce6146',
		'class_pt_issuenote.php' => '3c00056d5746c033152eae63dec8f6ed',
		'class_pt_issuesearch.php' => '6ffd0ea42ae63bff044384350ba68fdd',
		'class_pt_patch_parse.php' => 'a28a84657d3d79298b22231ec96ca417',
		'class_reportitem_pt.php' => 'dc0dd79927b34530af000194d9c47289',
		'class_upload_pt.php' => '637af6b275428e302f9c46e122e0306e',
		'class_upload_ptimporter.php' => '700e0d446984a48ad568c308a43d3d18',
		'functions_projecttools.php' => 'd5e77067219517cde6ecd2a9b91601c2',
		'functions_pt_digest.php' => '21c69c56d16ae7f17cca9f131e9612a3',
		'functions_pt_forumbit.php' => '7a610b110fe6cc1a705b946c5ecdb546',
		'functions_pt_impex.php' => '7e2bcb18ee646d401dbbdb02c139f32d',
		'functions_pt_milestone.php' => '680b3252b1a89eee069bb95712cc6555',
		'functions_pt_notehistory.php' => '925f774952c6182f129708a14be45f85',
		'functions_pt_patch.php' => 'a1e3a4a86e477f4756df407afd66f0e2',
		'functions_pt_posting.php' => 'bded35386634fdfa9a28c4cbf9da059f',
		'functions_pt_search.php' => 'adc127215833d8aa4f390d8fbee5746b',
		'functions_pt_timeline.php' => 'c40252bf4faaac605cf3bfa868d2ddc6',
		'functions_pt_usercp.php' => 'a695d917ba026c481f5b1ef4c04d452b',
		'functions_pt_usertools.php' => 'c3fbe71abb7292757f0f0c9bfd660191',
		'functions_ptimporter.php' => '940cc8532f4fdac43b2363ec7c6b7068',
	),
	'/includes/block' => array(
		'ptissues.php' => 'bb3c4176369741d903bc38834bf9d412',
	),
	'/includes/cron' => array(
		'pt_cleanup.php' => 'a8c3419d7443db9d4fe74cd3d938c087',
		'pt_digestdaily.php' => '94504011c7036b07e2d7d460407d2ab0',
		'pt_digestweekly.php' => 'eafa138b046d53a72742449bbf1304ca',
	),
	'/includes/xml' => array(
		'bitfield_vbprojecttools.xml' => 'bf7bb5a8e9381be36e727a6b421b0e20',
		'cpnav_vbprojecttools.xml' => '83ecad7f402e31e70c9bcc4a094dbcb0',
		'cssrollup_vbprojecttools.xml' => '65b969152897feff010c66cde098bce3',
		'hooks_vbprojecttools.xml' => '2a2c069747a9fd10ad20629f2491bd2b',
		'product-vbprojecttools.xml' => 'f4454242de47baf4d3fdd1e914887096',
	),
	'/install' => array(
		'vbulletin-mobile-style-pt.xml' => '23ae28e8dcea6ea36b7bb25d1a23c2a7',
	),
	'/packages/vbcms/item/widget' => array(
		'recentptcomments.php' => '6afc1d0cd440a667c43f62ce0170dfec',
		'recentptissues.php' => '1fad008712dd929863bfbb0f2577cf27',
	),
	'/packages/vbcms/widget' => array(
		'recentptcomments.php' => 'db88951ae8a2b2212123770b2f4f6cb5',
		'recentptissues.php' => '0dcac1f7f19f5539966d4d2600e6c355',
	),
	'/packages/vbprojecttools/search/indexcontroller' => array(
		'issuenote.php' => 'fd6421e426166a585104e368a5f44e86',
		'project.php' => 'e02c646ff5e06ca72bc76b9cf52954f9',
	),
	'/packages/vbprojecttools/search/result' => array(
		'issue.php' => '4b15c806acd7b64df8812daac5be0a67',
		'issuenote.php' => '1e18016ef5ec70c2c32071159022196f',
		'project.php' => '0691e1dcedf578a6006bb6e2ec42ae90',
	),
	'/packages/vbprojecttools/search/searchcontroller' => array(
		'newissuenote.php' => '261f6fa5b06e160ad581272e09f06df0',
	),
	'/packages/vbprojecttools/search/type' => array(
		'issue.php' => '3bcc68371bc26830c2edd78872bb4aa1',
		'issuenote.php' => 'b6624c034eb38b2bdb7eccde1af769ed',
		'project.php' => 'e619da95511b3e6a663ecc891d50cf39',
	),
	'/vb/activitystream/popularity/project' => array(
		'issue.php' => 'a816e45665616722c93209dc250bfb79',
	),
	'/vb/activitystream/populate/project' => array(
		'issue.php' => '7d92303ac5e4464d9bb16d3433a77fdb',
		'issuenote.php' => '7d47d71d18e752d7daedbd9e9161ec23',
	),
	'/vb/activitystream/view/perm/project' => array(
		'base.php' => '0241ad55e61f8b44944e6f13e1d0c38b',
		'issue.php' => '000fb3ec1f0c5ba7abc669217e992ba7',
		'issuenote.php' => '2eb72325c9bd9a66d4747952b943c4f9',
	),
	'/vb/legacy' => array(
		'issue.php' => '11914daf26ce44f115d711166957ae97',
		'issuenote.php' => '21dd5da7c9b99db0537049bdf139641a',
		'project.php' => '8601603a50d0720de094b1cd0efeb3e4',
	),
);
$md5_sum_softwareid = 'vbprojecttools';
$md5_sum_versions['vbprojecttools'] = '2.2.0';
?>
