<?php
// Checksum file
// Product: vbprojecttools - vBulletin Project Tools
// Version: 2.2.0
// File generated by: $RCSfile: mh_md5gen.php,v $ - $Revision: 2.0.1 $
// Generator: MD5 Version File generator by MarcoH64 and PitchouneN64ngc (c)

$md5_sums = array(
	'/' => array(
		'issue.php' => 'c31f05781abc8ec086b18a5ec97ebcdd',
		'issuelist.php' => '65caeba59b05554439ef70634b2a9744',
		'milestone.php' => 'c9737632f1b76d20b254a1073610f45d',
		'milestoneissuelist.php' => '3bd9e9df3a1fe1813c98690418777413',
		'project.php' => 'a42efde04781b87ec03f7af1f03af9f5',
		'projectajax.php' => '4bf416ea95461e3e0bc14fd469208866',
		'projectattachment.php' => '55bdb140c3be054939cf6debef7cee5e',
		'projectexternal.php' => '3061c7d906566e084bd2f73a5d3ea2de',
		'projectmilestone.php' => '4f0e7eb0b7a7ffcb9df351a845032c38',
		'projectpost.php' => '3b2db294b11475aee9b5502e70bf49c6',
		'projectsearch.php' => '29e66b81619dffb7b9f0af4428a1b3b7',
		'projecttimeline.php' => 'd2afb6adeaa2f6d6c0e7b9ef76b7e892',
	),
	'/admincp' => array(
		'project.php' => 'c577bc0523f70d7a088ebb86ca8f8f1b',
		'projectcategory.php' => '227ca7a0b3f02843ed53bc18010704a1',
		'projectcounters.php' => 'dd1cbad5464a9083fe1a2c190a6044ab',
		'projectmagicselect.php' => '3af7b4b66392d24f2b29426a7f2cbe05',
		'projectmilestone.php' => 'dfa0599be57576d5a06104c88fa4deeb',
		'projectpermission.php' => '0b30b9d0783862334458fed99e2d2012',
		'projectpriority.php' => '71ea46ec0263ae422d3ba56436a7cf2d',
		'projecttag.php' => '33e2a60262a438a9be4b8f3fb14bc413',
		'projecttype.php' => 'fcc8d9beca313d365ad592aecf077bdb',
		'projectversion.php' => '978bfdfc2d87a9b34c7e6479bdfa06c5',
	),
	'/archive' => array(
		'project.php' => '16aa8cbc161de22dbe580b8e7086d58c',
	),
	'/clientscript' => array(
		'vbulletin_list_builder.js' => '9a707a9c5a4b2a131e2cec0f5a5d2a79',
		'vbulletin_magic_select.js' => '83ef793b2d359865b732e9d5092c1186',
		'vbulletin_pt_ajax_issuelist.js' => 'c8e46aa46acc020c17c264ff73497040',
		'vbulletin_pt_issue.js' => 'b68188eb192f3bdeb80ab1f8698f1968',
		'vbulletin_pt_issuenote_loader.js' => '48f1a1aa0929d397c5cfab18388ee098',
		'vbulletin_pt_petition.js' => 'b34f65c31cea513eb89155e761a95f26',
		'vbulletin_pt_quick_reply.js' => 'c1800bb1f6e36a8de0d8592939d2c917',
		'vbulletin_pt_read_marker.js' => '05593b40ca72245dc41b11b4a1212707',
		'vbulletin_ptsearch_form.js' => '8607c59b5eadbbaa23a80dd84d7dc5b2',
		'vbulletin_quick_edit_issue.js' => 'ffd4a0a38ced687114c4d0dcfbe06a33',
		'vbulletin_quick_edit_issuenote.js' => '220e035adf112022eb7aa8ffa0e189c8',
	),
	'/images/buttons' => array(
		'project-hover.png' => 'dcde1da9e7446e1d80f95ac924fb7291',
		'project.png' => '7680167b9f54c35fd712fa166ef5ff13',
	),
	'/images/misc' => array(
		'issue_assigned.png' => 'd49c90aea57f6fc2ae8d8f599752f9f7',
		'issue_closed.png' => 'bc4263496ac6453a078ba3794c190a66',
		'issue_petition.png' => '57c43da89314e5d13efe5f44d9e795de',
		'issue_private.png' => '4252f2ec08e9d698e11962b7440def17',
	),
	'/images/site_icons' => array(
		'project.png' => '0d106e5b9b92a8d8e41c95e63ffeb08c',
	),
	'/images/statusicon' => array(
		'project_forum_new.png' => '0a76e7c36e19060b5475f8f3dceababe',
		'project_forum_new_16.png' => '26238617b11032142e6ee3821897c8c5',
		'project_forum_old.png' => 'd92ea6e6fc0ae0fb297c66ef5bb5ab2c',
		'project_forum_old_16.png' => 'f4c2e93a03e4a119b795a94495ec0db9',
		'pt_type_bug.png' => '198dfb2cc9a8f1d4c07002d7154bb960',
		'pt_type_feature.png' => 'ae971bbac7be861c0801d3c3654b3151',
		'pt_type_task.png' => '5bdb7d94a29290d45b87707e1baac956',
	),
	'/includes' => array(
		'adminfunctions_projecttools.php' => 'cb84878908185edaf4c128be6a879aef',
		'class_bbcode_pt.php' => '23d587f59db61c639c55228208283ad2',
		'class_dm_attachment_pt.php' => '0cc5c7958caaad1406430397f1a48251',
		'class_dm_pt_issue.php' => '7ef35c8430cd7b2bed210803b748bc28',
		'class_dm_pt_issueassign.php' => '2a4d86508f1956eb651602a638a53434',
		'class_dm_pt_issuechange.php' => 'c454843ac6827179a268d92bfaf1d7e5',
		'class_dm_pt_issuenote.php' => '30bc4578397d1b0bfbc0cf5e9c355293',
		'class_dm_pt_issuepetition.php' => '870bc7786e9195135dc201c70d98486e',
		'class_dm_pt_issuereport.php' => '50edb836d5f78d34cb7f0413e06623c1',
		'class_dm_pt_issuestatus.php' => '9b0450f8bd258e25519a7dc9b72d70a5',
		'class_dm_pt_issuesubscribe.php' => 'fcd95a010ddb12ced55b6ef1097e0cf7',
		'class_dm_pt_issuetype.php' => '76d575e150d35ef311dc2b0464cd6900',
		'class_dm_pt_issuevote.php' => '62afadb524fbc49112bcd3a1cc858f91',
		'class_dm_pt_magicselect.php' => '54c4dc17e4db1d18acd98575b09557fd',
		'class_dm_pt_milestone.php' => '3441e967009ee18a7ec18a5b1573bc8f',
		'class_dm_pt_project.php' => 'd72611b57aeb341e059385294908ee3c',
		'class_friendly_url_project.php' => 'ff727d2e2ae18ff4e4060ea9d0522aaf',
		'class_pt_impex.php' => '3d918326659f2f9c5e5fed3a8eff4721',
		'class_pt_issuelist.php' => 'a7101c31e2d301ec48467bb2adc605ee',
		'class_pt_issuenote.php' => 'd75f9ce0d94ce52ff72193c700830284',
		'class_pt_issuesearch.php' => 'a5d7590aaf4b4fce8e3835ebb9a8a45e',
		'class_pt_patch_parse.php' => 'f4bf8077d6a6b8445ae9ba83076488b8',
		'class_reportitem_pt.php' => '001552b429493d73c425f29f9be957a4',
		'functions_projecttools.php' => '72623ecdc12991915a913b4bda367e9b',
		'functions_pt_digest.php' => 'ea99e61ea7fa51503f82000ca96183eb',
		'functions_pt_forumbit.php' => '8c3b72d5fcdd1ee7c771f511b6cce543',
		'functions_pt_impex.php' => '12512e92bee4c931168ed1ab2b889c56',
		'functions_pt_milestone.php' => '81b135e28153eb5ce759bdd45cad1796',
		'functions_pt_notehistory.php' => '164b3d017951116ca2cde32c0ade5ee1',
		'functions_pt_patch.php' => 'ae6cf54a024f15bd81de2dee3568e355',
		'functions_pt_posting.php' => '98020e08b17afdb7ec0b0d68349b70c8',
		'functions_pt_search.php' => '8232bb964f3db641437cdf9218e7a350',
		'functions_pt_timeline.php' => '162574083ba01d186225325f55b6d883',
		'functions_pt_usercp.php' => 'c4ede5a3114c71e637367b1868541573',
		'functions_pt_usertools.php' => '2a2bc600852ce8cbc27fce96dda12253',
	),
	'/includes/block' => array(
		'ptissues.php' => '048bb01c360c2d7d5a6c353733ec52de',
	),
	'/includes/cron' => array(
		'digestweekly.php' => '0389002bc6dec8e108ceda88273a0933',
		'pt_cleanup.php' => 'd5a7ce54bf43f28fa1bf418554e1cdc3',
		'pt_digestdaily.php' => '5fd34fe502ceddba8d874120af461bf5',
	),
	'/includes/xml' => array(
		'bitfield_vbprojecttools.xml' => '79ead275973b5b49d74ad87839bd91db',
		'cpnav_vbprojecttools.xml' => '83ecad7f402e31e70c9bcc4a094dbcb0',
		'cssrollup_vbprojecttools.xml' => '65b969152897feff010c66cde098bce3',
		'hooks_vbprojecttools.xml' => '2a2c069747a9fd10ad20629f2491bd2b',
		'product-vbprojecttools.xml' => 'c0584c102fe8cb12d8a097cb428e3ff5',
	),
	'/install' => array(
		'vbulletin-mobile-style-pt.xml' => '23ae28e8dcea6ea36b7bb25d1a23c2a7',
	),
	'/packages/vbcms/item/widget' => array(
		'recentptcomments.php' => '58ae6feaf1aed7285f4fcb2e6b955b0a',
		'recentptissues.php' => 'e552509868ab11d615363f4ba0509e3f',
	),
	'/packages/vbcms/widget' => array(
		'recentptcomments.php' => 'e47e245404d641d2dd881545f31d342b',
		'recentptissues.php' => '894cbb134ce784100fceb239ff14373c',
	),
	'/packages/vbprojecttools/search/indexcontroller' => array(
		'issuenote.php' => '294fb74361e9b579bacbc08c521c28d9',
		'project.php' => '9ec57630916cb76960e2d9cbcb80a406',
	),
	'/packages/vbprojecttools/search/result' => array(
		'issue.php' => '371e66be3e777e9ba2ca9312870271b4',
		'issuenote.php' => '7f962140a7c12e123946284b57d30ba7',
		'project.php' => '49afc6eefe0f4d321f5749c876af45bb',
	),
	'/packages/vbprojecttools/search/searchcontroller' => array(
		'newissuenote.php' => '6eb8eaae397e4fab993f8619ee167bd0',
	),
	'/packages/vbprojecttools/search/type' => array(
		'issue.php' => '4738b496b2a82a6de77d6e296c068301',
		'issuenote.php' => 'b519782693ce68aae637993909f0a1f6',
		'project.php' => 'af01a211b6c464e4589fe0446aa890ec',
	),
	'/vb/activitystream/popularity/project' => array(
		'issue.php' => 'b01cc13ef7fe0e61e7eb5fa6381051ef',
	),
	'/vb/activitystream/populate/project' => array(
		'issue.php' => '573fac83598cd259c91290ace4848fff',
		'issuenote.php' => '42377341b96a50f34bae9c283d0c45d1',
	),
	'/vb/activitystream/view/perm/project' => array(
		'base.php' => '515a8ce065fd18f269ed3d979b4fc942',
		'issue.php' => 'b0d5919380f10a3767fd5406783bb803',
		'issuenote.php' => '621d6491b7c0ce1840b0ccc9f0c6b31b',
	),
	'/vb/legacy' => array(
		'issue.php' => 'ae7b5f709b8c2f5cd4464f3aab3bbc3e',
		'issuenote.php' => 'c9617c9dc8ceaeb51a383fbae32d58f7',
		'project.php' => '8fd758c946d9c530682b0c6fb3e2850a',
	),
);
$md5_sum_softwareid = 'vbprojecttools';
$md5_sum_versions['vbprojecttools'] = '2.2.0';
?>
